###   Find All Content
GET http://localhost:8080/api/content

###   Get Content by ID
GET http://localhost:8080/api/content


###   Create New Content
POST http://localhost:8080/api/content

Content-Type: application/json

{
  "id": 2,
  "title": "My Second Blog Post",
  "desc": "My Second Blog Post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-02-13T10:25:02.838496",
  "dateUpdated": null,
  "url": ""
}

